### ISSUE TITLE
Build issues on jekyll 3.

### ISSUE THREAD

**Issue by siadevelopment** [18F/jekyll_pages_api#29]
Hello, I have a jekyll 3 blog, and I'm having problems building my site with jekyll build. if I do bundle exec jekyll build it works correctly, however when I run vanilla jekyll build (with --trace) I get: 

```
WARN: Unresolved specs during Gem::Specification.reset:
      listen (~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /home/ubuntu/minimal-mistakes/_config.yml
/var/lib/gems/2.2.0/gems/jekyll_pages_api-0.1.5/lib/jekyll/site.rb:7:in `alias_method': undefined method `render' for class `Jekyll::Site' (NameError)
	from /var/lib/gems/2.2.0/gems/jekyll_pages_api-0.1.5/lib/jekyll/site.rb:7:in `<class:Site>'
	from /var/lib/gems/2.2.0/gems/jekyll_pages_api-0.1.5/lib/jekyll/site.rb:5:in `<module:Jekyll>'
	from /var/lib/gems/2.2.0/gems/jekyll_pages_api-0.1.5/lib/jekyll/site.rb:4:in `<top (required)>'
	from /var/lib/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:30:in `process'
	from /var/lib/gems/2.2.0/gems/jekyll-3.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /var/lib/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
	from /var/lib/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
	from /var/lib/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
	from /var/lib/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
	from /var/lib/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
	from /var/lib/gems/2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
	from /var/lib/gems/2.2.0/gems/jekyll-3.0.0/bin/jekyll:17:in `<top (required)>'
	from /usr/local/bin/jekyll:23:in `load'
	from /usr/local/bin/jekyll:23:in `<main>'
```

My installed bundles are:

```
ubuntu@ip-172-31-16-45:~/minimal-mistakes$ bundle install
Using rake 10.4.2
Using addressable 2.3.8
Using sass 3.4.19
Using thor 0.19.1
Using bourbon 4.2.6
Using i18n 0.7.0
Using colorize 0.7.7
Using net-ssh 3.0.1
Using net-scp 1.2.1
Using sshkit 1.7.1
Using capistrano 3.4.0
Using capistrano-jekyll 0.1.0
Using colorator 0.1
Using colored 1.2
Using ffi 1.9.10
Using ethon 0.8.0
Using mercenary 0.3.5
Using mini_portile 0.6.2
Using nokogiri 1.6.6.3
Using parallel 1.6.1
Using typhoeus 0.8.0
Using yell 2.0.5
Using html-proofer 2.5.2
Using htmlentities 4.3.4
Using jekyll-sass-converter 1.3.0
Using rb-fsevent 0.9.6
Using rb-inotify 0.9.5
Using listen 3.0.3
Using jekyll-watch 1.3.0
Using kramdown 1.9.0
Using liquid 3.0.6
Using rouge 1.10.1
Using safe_yaml 1.0.4
Using jekyll 3.0.0
Using jekyll-archives 2.1.0 from https://github.com/jekyll/jekyll-archives.git (at master)
Using jekyll-sitemap 0.8.0
Using jekyll_frontmatter_tests 0.0.5
Using jekyll_pages_api 0.1.5
Using octopress-deploy 1.3.0
Using octopress-hooks 2.6.1
Using octopress-escape-code 2.0.6
Using redcarpet 3.3.2
Using titlecase 0.1.1
Using octopress 3.0.11
Using bundler 1.10.6
Bundle complete! 10 Gemfile dependencies, 45 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

Thanks!

**Comment by afeld** [comment]
Sorry for taking so long to respond to this—are you still having the issue? Is the source code for the site available somewhere?

**Comment by afeld** [comment]
Closing as stale, but feel free to re-open if you (or anyone else) runs into the same issue!
